apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcp-dr-oadp-operator
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/CHANGEME_ORG/hcp-dr-oadp-gitops.git
    targetRevision: main
    path: manifests/oadp/operator
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-adp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
