apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hcp1-data-plane-demo

configMapGenerator:
  - name: arcade-demo-html
    options:
      disableNameSuffixHash: true
    files:
      - index.html

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
